### PR TITLE
Fix invalid base URL error

### LINKED ISSUE #7850: [Bug]: ui issue admin panel
### What happened?

can't access admin panel with last main version 
invalide base url reported in 117-7e4422a742f8f04c.js

in logs I see :
TypeError: Failed to construct 'URL': Invalid base URL
 
117-7e4422a742f8f04c.js
 
@yujonglee @krrishdholakia 

### Relevant log output

```shell
Application error: a client-side exception has occurred (see the browser console for more information).
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.58.4

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by yujonglee**
## Title

Fix invalid base URL error

## Relevant issues

Resolves #7850

## Type

🐛 Bug Fix

### CODE REVIEW

File: ui/litellm-dashboard/src/components/create_user_button.tsx [hunk 1]
```diff
@@ -54,9 +54,7 @@ const Createuser: React.FC<CreateuserProps> = ({
   const router = useRouter();
   const isLocal = process.env.NODE_ENV === "development";
 
-  const [baseUrl, setBaseUrl] = useState(
-    isLocal ? "http://localhost:4000" : "",
-  );
+  const [baseUrl, setBaseUrl] = useState("http://localhost:4000");
```
Comment (ghost) [inline ui/litellm-dashboard/src/components/create_user_button.tsx:57]: this should probably be globally accessible - i'm fixing the same issue right now on the admin panel
