### PR TITLE
fixed user id passed as null when keyuser is you

### LINKED ISSUE #8027: [Bug]: UI - Need to refresh screen when key delete, key creation op done
### The Feature

If you delete a Key for example  the screen is not refreshed, you need to refresh it manually. ( same for tema and key creation if I remember well so near all screens whre you cna add or delete things 

think we need a refresh each time an action is done what change the screen results 

### Motivation, pitch

improve the user's journey 

### Are you a ML Ops Team?

Yes

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by jaswanth8888**
## Title

fixed user id passed as null when keyuser is you

## Relevant issues

user id is being sent as null when internalUser/any user creates key when ownedby is you. as result of which key created by the user doesn't show up after a page refresh.

also fixes #8027

## Type

🐛 Bug Fix

## Changes

changes was made in create_key_button.tsx file

## [REQUIRED] Testing - Attach a screenshot of any new tests passing locally
image

### CODE REVIEW

File: ui/litellm-dashboard/src/components/create_key_button.tsx [hunk 1]
```diff
@@ -160,6 +160,9 @@ const CreateKey: React.FC<CreateKeyProps> = ({
       message.info("Making API Call");
       setIsModalVisible(true);
 
+      if(keyOwner === "you"){
```
Comment (ghost) [inline ui/litellm-dashboard/src/components/create_key_button.tsx:163]: when is keyowner !=== you? on the ui

Comment (jaswanth8888) [reply ui/litellm-dashboard/src/components/create_key_button.tsx:163]: when user changes to service account or create for another user
