### PR TITLE
Litellm fix icons

### LINKED ISSUE #9343: [Feature]: Web UI llms providers icons logos hosted from local host
### The Feature

litellm/ui/litellm-dashboard/src/components/provider_info_helpers.tsx

```ts
  export const providerLogoMap: Record<string, string> = {
    [Providers.OpenAI]: "https://artificialanalysis.ai/img/logos/openai_small.svg",
    [Providers.OpenAI_Text]: "https://artificialanalysis.ai/img/logos/openai_small.svg",
    [Providers.OpenAI_Text_Compatible]: "https://artificialanalysis.ai/img/logos/openai_small.svg",
    [Providers.OpenAI_Compatible]: "https://artificialanalysis.ai/img/logos/openai_small.svg",
    [Providers.Azure]: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg",
    [Providers.Azure_AI_Studio]: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Microsoft_Azure_Logo.svg",
    [Providers.Anthropic]: "https://artificialanalysis.ai/img/logos/anthropic_small.svg",
    [Providers.Google_AI_Studio]: "https://artificialanalysis.ai/img/logos/google_small.svg",
    [Providers.Bedrock]: "https://artificialanalysis.ai/img/logos/aws_small.png",
    [Providers.Groq]: "https://artificialanalysis.ai/img/logos/groq_small.png",
    [Providers.MistralAI]: "https://artificialanalysis.ai/img/logos/mistral_small.png",
    [Providers.Cohere]: "https://artificialanalysis.ai/img/logos/cohere_small.png",
    [Providers.Vertex_AI]: "https://artificialanalysis.ai/img/logos/google_small.svg",
    [Providers.Databricks]: "https://artificialanalysis.ai/img/logos/databricks_small.png",
    [Providers.Ollama]: "https://artificialanalysis.ai/img/logos/ollama_small.svg",
    [Providers.xAI]: "https://artificialanalysis.ai/img/logos/xai_small.svg",
    [Providers.Deepseek]: "https://artificialanalysis.ai/img/logos/deepseek_small.jpg",
    [Providers.AssemblyAI]: "https://artificialanalysis.ai/img/logos/assemblyai_small.png",
    [Providers.Cerebras]: "https://artificialanalysis.ai/img/logos/cerebras_small.png",
    [Providers.Sambanova]: "https://artificialanalysis.ai/img/logos/sambanova_small.webp",
    [Providers.Perplexity]: "https://artificialanalysis.ai/img/logos/perplexity_small.png",
    [Providers.TogetherAI]: "https://artificialanalysis.ai/img/logos/togetherai_small.svg",
    [Providers.Openrouter]: "https://t0.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://openrouter.ai/chat&size=256",
    [Providers.FireworksAI]: "https://artificialanalysis.ai/img/logos/fireworks_small_revised.png"

};
```

Why are those providers icons not included in the repository as local images?
artificialanalysis is slooooow
Loading a big list of models on the UI causes gigantic delays during open list / especial that some of those logos are not available.

**Propose**: download images and include in repo as `/public/` - ui/litellm-dashboard/public/
This will speed up loading page as images will be hosted/provided directly from UI host.

### Motivation, pitch

Delay loading page

Image

Icons are loaded few times during open Model page

Image

### Are you a ML Ops Team?

No

### Twitter / LinkedIn details

@arturzdolinski https://www.linkedin.com/in/artur-zdolinski/

### PR DESCRIPTION
**Pull request by azdolinski**
## Title
Replace external "artificialanalysis.ai" icons by local svg

## Relevant issues
Fix #9343 

## Pre-Submission checklist

**Please complete all items before asking a LiteLLM maintainer to review your PR**

- [ ] I have Added testing in the `tests/litellm/` directory, **Adding at least 1 test is a hard requirement** - [see details](https://docs.litellm.ai/docs/extras/contributing_code)
- [x] I have added a screenshot of my new test passing locally 
- [x] My PR passes all unit tests on (`make test-unit`)[https://docs.litellm.ai/docs/extras/contributing_code]
- [x] My PR's scope is as isolated as possible, it only solves 1 specific problem

## Type
🐛 Bug Fix
🧹 Refactoring

## Changes
Proposal how to fix icon to store them in: `ui/litellm-dashboard/public/assets/logos` as local png/svg files.

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
wow amazing work @azdolinski

File: ui/litellm-dashboard/src/components/provider_info_helpers.tsx [hunk 1]
```diff
@@ -2,171 +2,172 @@ import OpenAI from "openai";
...
+  AssemblyAI: "assemblyai",
+  Cerebras: "cerebras",
+  Sambanova: "sambanova",
+  Perplexity: "perplexity",
+  TogetherAI: "togetherai",
+  Openrouter: "openrouter",
+  FireworksAI: "fireworks_ai"
 };
 
-export const providerLogoMap: Record<string, string> = {
```
Comment (ishaan-jaff) [inline ui/litellm-dashboard/src/components/provider_info_helpers.tsx:59]: please only change this section. nothing else is needed to change correct

**Review by ishaan-jaff — CHANGES_REQUESTED** [review]
please show screenshot of models page loading

File: ui/litellm-dashboard/src/components/provider_info_helpers.tsx (hunk 1 above)
Comment (azdolinski) [reply ui/litellm-dashboard/src/components/provider_info_helpers.tsx:59]: done, 
sorry.. my linter run during commit

**Comment by ishaan-jaff** [comment]
confirmed this worked for me

**Comment by ishaan-jaff** [comment]
great work @azdolinski would you be open to working with us on LiteLLM as a founding engineer ? (I'm impressed by your work on this)

If this sounds interesting here's my cal, please book some time: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
