### PR TITLE
fix-spend-logs

### LINKED ISSUE #20401: [Bug]: Spend logs on v1.81.7 loading really slow
### Check for existing issues

- [x] I have searched the existing issues and checked that my issue is not a duplicate.

### What happened?

as title said: Spend logs on v1.81.7 loading really slow. It's be problem from API responses i think. It's just loading 15-20 seconds. On older version spend logs working smooth.

### Steps to Reproduce

open spend logs

### Relevant log output

```shell

```

### What part of LiteLLM is this about?

_No response_

### What LiteLLM version are you on ?

v1.81.7

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by OrionCodeDev**
# Fix: Spend Logs UI causes N+1 request storm and crashes LiteLLM instances

## Relevant issues

Fixes #19555
Fixes #20401

Related discussion: After 1-2 hours of running LiteLLM, navigating to Spend Logs tab in UI causes extremely slow loading or crashes the LiteLLM process entirely.

## Type

🐛 Bug Fix

### Problem Analysis

When a user opens the **Spend Logs** tab in the LiteLLM UI, the following happens:

1. **One API call** fetches the paginated list of 50 logs: `GET /spend/logs/ui?page=1&page_size=50`
2. **Immediately after**, the UI fires off **50 parallel API calls** — one for each log — to fetch detailed request/response data: `GET /spend/logs/ui/{request_id}` × 50

This means **every page load generates 51 HTTP requests** instead of 1.

With **Live Tail enabled** (auto-refresh every 15 seconds), this compounds dramatically:
- Every 15 seconds: 51 requests
- Per hour: ~12,240 requests
- Over 1-2 hours: **~24,000+ requests** just from the Spend Logs tab

Each `/spend/logs/ui/{request_id}` call on the backend iterates through all registered custom loggers calling `get_request_response_payload()`, which can be expensive. This avalanche of requests overwhelms the backend, leading to extreme slowness or process crashes.

Additionally, the backend endpoint had `@lru_cache(maxsize=128)` applied to an `async` function. Python's `lru_cache` does not work with async functions — it caches the coroutine object rather than the resolved result, leading to incorrect behavior and potential memory issues.

### Root Cause

The root cause is in `ui/litellm-dashboard/src/components/view_logs/prefetch.ts` which is called from the main logs `useQuery` in `index.tsx`:

```typescript
// prefetch.ts - fires for ALL 50 logs immediately
const promises = logs.map((log) => {
  return queryClient.prefetchQuery({
    queryFn: async () => {
      return await uiSpendLogDetailsCall(accessToken, log.request_id, formattedStartTime);
    },
  });
});
await Promise.all(promises); // 50 concurrent requests!
```

This was called inside the main `useQuery` that also runs on every Live Tail refresh cycle.

#### 1. Remove aggressive prefetching (`index.tsx`)

**File:** `ui/litellm-dashboard/src/components/view_logs/index.tsx`

- Removed `import { prefetchLogDetails } from "./prefetch"` 
- Removed the `await prefetchLogDetails(response.data, ...)` call from the main logs `useQuery`
- Removed the `response.data.map()` block that injected prefetched data back into log entries

The table columns (`columns.tsx`) only use lightweight fields like `startTime`, `status`, `model`, `spend`, `tokens`, `request_id`, etc. — none of which require the expensive messages/response payload. So the list endpoint alone provides everything needed for the table view.

**Before:** 1 list request + 50 detail requests = 51 requests per page load
**After:** 1 list request = 1 request per page load

#### 2. Lazy-load details on demand (`LogDetailsDrawer.tsx`)

**File:** `ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx`

- Added new props: `accessToken?: string` and `startTime?: string` to `LogDetailsDrawerProps`
- Added a `useQuery` hook that fetches log details (messages/response) **only when the drawer is open** — i.e., when the user clicks on a specific log row:

```typescript
const logDetails = useQuery({
  queryKey: ["logDetails", logEntry?.request_id, startTime],
  queryFn: async () => {
    if (!accessToken || !logEntry?.request_id || !startTime) return null;
    return await uiSpendLogDetailsCall(accessToken, logEntry.request_id, startTime);
  },
  enabled: open && !!accessToken && !!logEntry?.request_id && !!startTime,
  staleTime: 10 * 60 * 1000, // 10 minutes cache
  gcTime: 10 * 60 * 1000,
});
```

- The fetched messages/response are merged with existing log data via `effectiveMessages` and `effectiveResponse` variables
- Updated `getRawRequest()` and `getFormattedResponse()` to use the lazy-loaded data
- Added a loading spinner (`<Spin>`) while details are being fetched
- The `missingData` check now accounts for loading state to avoid premature "missing data" warnings
- Results are cached for 10 minutes via React Query, so re-opening the same log doesn't trigger another API call

The parent `index.tsx` now passes `accessToken` and `startTime` to the drawer component.

#### 3. Remove broken `@lru_cache` on async endpoint (`spend_management_endpoints.py`)

**File:** `litellm/proxy/spend_tracking/spend_management_endpoints.py`

- Removed `@lru_cache(maxsize=128)` decorator from the `async def ui_view_request_response_for_request_id()` endpoint

Python's `functools.lru_cache` is designed for synchronous functions. When applied to an `async` function, it caches the coroutine object itself rather than the awaited result. This means:
- The cache never actually works (each call creates a new coroutine)
- Previously cached coroutines may have already been consumed, leading to errors
- It can cause memory leaks since coroutine objects may hold references

Added a comment explaining why the decorator was removed.

### Impact Summary

| Metric | Before | After |
|--------|--------|-------|
| Requests per page load | 51 (1 list + 50 details) | 1 (list only) |
| Requests per row click | 0 (prefetched) | 1 (lazy loaded) |
| Live Tail requests per 15s | 51 | 1 |
| Requests over 2 hours (Live Tail) | ~24,000+ | ~480 |
| Detail data cached | 10 min (React Query) | 10 min (React Query) |

### What was NOT changed

- The `/spend/logs/ui` list endpoint — no backend changes needed; it already returns lightweight paginated data
- The `/spend/logs/ui/{request_id}` detail endpoint — only the `@lru_cache` decorator was removed; the endpoint logic remains unchanged
- The `prefetch.ts` file — left in place (unused now) in case it's useful for future single-item prefetch scenarios
- The `columns.tsx` table column definitions — no changes needed
- Audit logs, session logs, and all other tabs — completely unaffected
- Keyboard navigation (J/K) in the drawer — still works; details load when navigating to a new log

### Testing Notes

- Verified that the table columns don't depend on `messages` or `response` fields
- The drawer now shows a loading spinner while fetching details, then renders the full request/response view once loaded
- Navigating between logs with keyboard shortcuts (J/K) triggers a new lazy fetch for each log (cached for 10 min)
- Live Tail auto-refresh now only refreshes the lightweight list — no detail prefetching
- Error states (failed requests) still display correctly since error info comes from `metadata.error_information` which is available in the list response

### CODE REVIEW

File: ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx [hunk 1]
```diff
@@ -76,16 +82,35 @@ export function LogDetailsDrawer({
     onSelectLog,
   });
 
+  // Lazy-load log details (messages/response) only when drawer is open
+  // This fetches data for a single log on-demand instead of prefetching all 50
+  const logDetails = useQuery({
```
[the remark this answers is not in the document]
Comment (OrionCodeDev) [reply ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx]: Check new commit

**Comment by OrionCodeDev** [comment]
@yuneng-jiang maybe you can look into this? I don't know who be responisible of UI and can accept UI changes.
It's small change. It's fast, smooth and don't lagging backend server anymore.

**Comment by krrishdholakia** [comment]
under review, thanks for bumping this @superpoussin22

File: litellm/proxy/spend_tracking/spend_management_endpoints.py [hunk 2]
```diff
@@ -1862,7 +1861,8 @@ def parse_date(date_str: str) -> datetime:
         raise handle_exception_on_proxy(e)
 
 
-@lru_cache(maxsize=128)
+# NOTE: @lru_cache was removed here because it does not work correctly with async functions.
```
Comment (yuneng-jiang) [inline litellm/proxy/spend_tracking/spend_management_endpoints.py]: Nit: We can remove the comments here

File: ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx [hunk 3]
```diff
@@ -45,6 +47,8 @@ export interface LogDetailsDrawerProps {
   onOpenSettings?: () => void;
   allLogs?: LogEntry[];
   onSelectLog?: (log: LogEntry) => void;
+  accessToken?: string;
```
Comment (yuneng-jiang) [inline ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx]: accessToken is available on the useAuthorized hook, you should use this in order to prevent prop drilling. Be sure to update the tests as well.

File: ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx (hunk 1 above)
Comment (yuneng-jiang) [inline ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx]: This should be in its own file inside of src/app/(dashboard)/hooks

File: ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx [hunk 4]
```diff
@@ -76,16 +82,35 @@ export function LogDetailsDrawer({
...
+    },
+    enabled: open && !!accessToken && !!logEntry?.request_id && !!startTime,
+    staleTime: 10 * 60 * 1000, // 10 minutes
+    gcTime: 10 * 60 * 1000, // 10 minutes
+  });
+
   if (!logEntry) return null;
 
+  // Merge lazy-loaded details into the log entry
+  const detailsData = logDetails.data as any;
```
Comment (yuneng-jiang) [inline ui/litellm-dashboard/src/components/view_logs/LogDetailsDrawer/LogDetailsDrawer.tsx:189]: not sure why we will need to merge, did you run into run into cases where the `detailsData` did not have everything you needed?

File: ui/litellm-dashboard/src/components/view_logs/index.tsx [hunk 5]
```diff
@@ -28,7 +28,7 @@ import { ErrorViewer } from "./ErrorViewer";
 import { useLogFilterLogic } from "./log_filter_logic";
 import { LogDetailsDrawer } from "./LogDetailsDrawer";
 import { getTimeRangeDisplay } from "./logs_utils";
-import { prefetchLogDetails } from "./prefetch";
+import { ERROR_CODE_OPTIONS, QUICK_SELECT_OPTIONS } from "./constants";
```
Comment (yuneng-jiang) [inline ui/litellm-dashboard/src/components/view_logs/index.tsx]: This fails the build due to identical imports

File: ui/litellm-dashboard/src/components/view_logs/index.tsx [hunk 6]
```diff
@@ -75,7 +75,7 @@ export default function SpendLogsTable({
   const quickSelectRef = useRef<HTMLDivElement>(null);
 
   // New state variables for Start and End Time
-  const [startTime, setStartTime] = useState<string>(moment().subtract(24, "hours").format("YYYY-MM-DDTHH:mm"));
+  const [startTime, setStartTime] = useState<string>(moment().subtract(4, "hours").format("YYYY-MM-DDTHH:mm"));
```
Comment (yuneng-jiang) [inline ui/litellm-dashboard/src/components/view_logs/index.tsx]: Can you elaborate on why you are changing this to 4 hours?

**Review by yuneng-jiang — CHANGES_REQUESTED** [review]
This is a great idea. Thanks for the contribution! Left some comments to request changes, and to get the thought process behind some changes.

File: litellm/proxy/spend_tracking/spend_management_endpoints.py [hunk 7]
```diff
@@ -1865,13 +1864,87 @@ def parse_date(date_str: str) -> datetime:
...
         )
 
-        # Get paginated data
-        data = await prisma_client.db.litellm_spendlogs.find_many(
-            where=where_conditions,
-            order=order_clause,
-            skip=skip,
-            take=page_size,
-        )
+        # Build raw SQL to fetch paginated data WITHOUT heavy columns
```
Comment (yuneng-jiang) [inline litellm/proxy/spend_tracking/spend_management_endpoints.py:1867]: Looks like the scope of this PR was expanded. It is not immediately obvious why you need a raw query for this. If you are omitting rows, wouldn't the `select` field on the prisma client suffice? Please elaborate on why you need a raw query.

**Review by yuneng-jiang — CHANGES_REQUESTED** [review]
I also see some merge conflicts, please adjust those as well. In general we want PRs to be isolated in the case we need to revert. This PR's scope has been expanded from frontend focused fetching to writing raw queries. I suggest having separate PRs for these

**Comment by yuneng-jiang** [comment]
Thanks for this! I did some manual testing and everything looks good. However this breaks all of the current tests around this endpoint, but I can take it from here. Planning to merge it into a different branch first, then adjusts the tests before merging into main
