### PR TITLE
Fix wrong URL for internal user invitation

### LINKED ISSUE #7191: [Bug]: In the Admin UI, the invitation link for the Internal User is missing a "/".
### What happened?

image

### Relevant log output

_No response_

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.54.0

### Twitter / LinkedIn details

_No response_

### PR DESCRIPTION
**Pull request by yujonglee**
## Title
Fix wrong URL for internal user invitation

## Relevant issues
Resolves #7191 

## Type

🐛 Bug Fix
🧹 Refactoring

## Changes

Avoid doing URL manipulation via string. Replace them with `new URL()`.

### CODE REVIEW

File: ui/litellm-dashboard/src/components/create_user_button.tsx [hunk 1]
```diff
@@ -81,27 +79,26 @@ const Createuser: React.FC<CreateuserProps> = ({
...
   useEffect(() => {
-    if (router) {
-      const { protocol, host } = window.location;
-      const baseUrl = `${protocol}/${host}`;
-      setBaseUrl(baseUrl);
+    if (!router) {
+      return;
     }
+
+    const base = new URL("/", window.location.href);
```
Comment (yujonglee) [inline ui/litellm-dashboard/src/components/create_user_button.tsx:100]: This

File: ui/litellm-dashboard/src/components/onboarding_link.tsx [hunk 2]
```diff
@@ -50,9 +42,9 @@ const OnboardingModal: React.FC<OnboardingProps> = ({
 
   const getInvitationUrl = () => {
     if (invitationLinkData?.has_user_setup_sso) {
-      return `${baseUrl}/ui`;
+      return new URL("/ui", baseUrl).toString();
     }
-    return `${baseUrl}/ui?invitation_id=${invitationLinkData?.id}`;
+    return new URL(`/ui?invitation_id=${invitationLinkData?.id}`, baseUrl).toString();
```
Comment (yujonglee) [inline ui/litellm-dashboard/src/components/onboarding_link.tsx:47]: This

**Review by yujonglee — COMMENTED** [review]
We should adopt this pattern everywhere so that we can avoid this kind of bug :)
